/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-113445-ge0da916b8f-20240129"
#endif /* AVUTIL_FFVERSION_H */
